<template><div><h1 id="get-started" tabindex="-1"><a class="header-anchor" href="#get-started"><span>Get started</span></a></h1>
<h2 id="installation" tabindex="-1"><a class="header-anchor" href="#installation"><span>Installation</span></a></h2>
<p><strong>ReplayBG</strong> can be installed via pypi by simply</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line">pip install py<span class="token operator">-</span>replay<span class="token operator">-</span>bg</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="requirements" tabindex="-1"><a class="header-anchor" href="#requirements"><span>Requirements</span></a></h3>
<ul>
<li>Python &gt;= 3.11</li>
<li>List of Python packages in <code v-pre>requirements.txt</code></li>
</ul>
<h2 id="preparation-imports-setup-and-data-loading" tabindex="-1"><a class="header-anchor" href="#preparation-imports-setup-and-data-loading"><span>Preparation: imports, setup, and data loading</span></a></h2>
<p>First of all import the core modules:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line"><span class="token keyword">import</span> os</span>
<span class="line"><span class="token keyword">import</span> numpy <span class="token keyword">as</span> np</span>
<span class="line"><span class="token keyword">import</span> pandas <span class="token keyword">as</span> pd</span>
<span class="line"></span>
<span class="line"><span class="token keyword">from</span> multiprocessing <span class="token keyword">import</span> freeze_support</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Here, <code v-pre>os</code> will be used to manage the filesystem, <code v-pre>numpy</code> and <code v-pre>pandas</code> to manipulate and manage the data to be used, and
<code v-pre>multiprocessing.freeze_support</code> to enable multiprocessing functionalities and run the twinning procedure in a faster,
parallelized way.</p>
<p>Then, we will import the necessary ReplayBG modules:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line"><span class="token keyword">from</span> py_replay_bg<span class="token punctuation">.</span>py_replay_bg <span class="token keyword">import</span> ReplayBG</span>
<span class="line"><span class="token keyword">from</span> py_replay_bg<span class="token punctuation">.</span>visualizer <span class="token keyword">import</span> Visualizer</span>
<span class="line"><span class="token keyword">from</span> py_replay_bg<span class="token punctuation">.</span>analyzer <span class="token keyword">import</span> Analyzer</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Here, <code v-pre>ReplayBG</code> is the core ReplayBG object (more information in the <RouteLink to="/documentation/replaybg_object.html">The ReplayBG Object</RouteLink> page),
while <code v-pre>Analyzer</code> and <code v-pre>Visualizer</code> are utility objects that will be used to
respectively analyze and visualize the results that we will produce with ReplayBG
(more information in the (<RouteLink to="/documentation/visualizing_replay_results.html">Visualizing Replay Results</RouteLink> and
<RouteLink to="/documentation/analyzing_replay_results.html">Analyzing Replay Results</RouteLink> pages).</p>
<p>Next steps consist of setting up some variables that will be used by ReplayBG environment.
First of all, we will run the twinning procedure in a parallelized way so let's start with:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line"><span class="token keyword">if</span> __name__ <span class="token operator">==</span> <span class="token string">'__main__'</span><span class="token punctuation">:</span></span>
<span class="line">    freeze_support<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>Then, we will set the verbosity of ReplayBG:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line">    verbose <span class="token operator">=</span> <span class="token boolean">True</span></span>
<span class="line">    plot_mode <span class="token operator">=</span> <span class="token boolean">False</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>Then, we need to decide what blueprint to use for twinning the data at hand.</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line">    blueprint <span class="token operator">=</span> <span class="token string">'multi-meal'</span></span>
<span class="line">    save_folder <span class="token operator">=</span> os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>join<span class="token punctuation">(</span>os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>abspath<span class="token punctuation">(</span><span class="token string">''</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token string">'..'</span><span class="token punctuation">,</span><span class="token string">'..'</span><span class="token punctuation">,</span><span class="token string">'..'</span><span class="token punctuation">)</span></span>
<span class="line">    parallelize <span class="token operator">=</span> <span class="token boolean">True</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>For more information on how to choose a blueprint, please refer to the <RouteLink to="/documentation/choosing_blueprint.html">Choosing Blueprint</RouteLink> page.</p>
<p>Now, let's load some data to play with. In this example, we will use the data stored in <code v-pre>example/data/data_day_1.csv</code>
which contains a day of data of a patient with T1D:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line">data <span class="token operator">=</span> pd<span class="token punctuation">.</span>read_csv<span class="token punctuation">(</span>os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>join<span class="token punctuation">(</span>os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>abspath<span class="token punctuation">(</span><span class="token string">''</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'..'</span><span class="token punctuation">,</span> <span class="token string">'data'</span><span class="token punctuation">,</span> <span class="token string">'data_day_1.csv'</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">data<span class="token punctuation">.</span>t <span class="token operator">=</span> pd<span class="token punctuation">.</span>to_datetime<span class="token punctuation">(</span>data<span class="token punctuation">[</span><span class="token string">'t'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><div class="hint-container warning">
<p class="hint-container-title">Warning</p>
<p>Be careful, data in PyReplayBG must be provided in a <code v-pre>.csv.</code> file that must follow some strict requirements. For more
information see the <a href="./data_requirements">Data Requirements</a> page.</p>
</div>
<p>Let's also load the patient information (i.e., body weight and basal insulin <code v-pre>u2ss</code>) stored in the <code v-pre>example/data/patient_info.csv</code> file.</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line">patient_info <span class="token operator">=</span> pd<span class="token punctuation">.</span>read_csv<span class="token punctuation">(</span>os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>join<span class="token punctuation">(</span>os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>abspath<span class="token punctuation">(</span><span class="token string">''</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'..'</span><span class="token punctuation">,</span> <span class="token string">'data'</span><span class="token punctuation">,</span> <span class="token string">'patient_info.csv'</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">p <span class="token operator">=</span> np<span class="token punctuation">.</span>where<span class="token punctuation">(</span>patient_info<span class="token punctuation">[</span><span class="token string">'patient'</span><span class="token punctuation">]</span> <span class="token operator">==</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token comment"># Set bw and u2ss</span></span>
<span class="line">bw <span class="token operator">=</span> <span class="token builtin">float</span><span class="token punctuation">(</span>patient_info<span class="token punctuation">.</span>bw<span class="token punctuation">.</span>values<span class="token punctuation">[</span>p<span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">u2ss <span class="token operator">=</span> <span class="token builtin">float</span><span class="token punctuation">(</span>patient_info<span class="token punctuation">.</span>u2ss<span class="token punctuation">.</span>values<span class="token punctuation">[</span>p<span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Finally, instantiate a <code v-pre>ReplayBG</code> object:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line">rbg <span class="token operator">=</span> ReplayBG<span class="token punctuation">(</span>blueprint<span class="token operator">=</span>blueprint<span class="token punctuation">,</span> save_folder<span class="token operator">=</span>save_folder<span class="token punctuation">,</span></span>
<span class="line">               yts<span class="token operator">=</span><span class="token number">5</span><span class="token punctuation">,</span> exercise<span class="token operator">=</span><span class="token boolean">False</span><span class="token punctuation">,</span></span>
<span class="line">               seed<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">,</span></span>
<span class="line">               verbose<span class="token operator">=</span>verbose<span class="token punctuation">,</span> plot_mode<span class="token operator">=</span>plot_mode<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="step-1-creation-of-the-digital-twin" tabindex="-1"><a class="header-anchor" href="#step-1-creation-of-the-digital-twin"><span>Step 1: Creation of the digital twin</span></a></h2>
<p>To create the digital twin, i.e., run the twinning procedure, using the MCMC method, use the <code v-pre>rbg.twin()</code> method:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line">rbg<span class="token punctuation">.</span>twin<span class="token punctuation">(</span>data<span class="token operator">=</span>data<span class="token punctuation">,</span> bw<span class="token operator">=</span>bw<span class="token punctuation">,</span> save_name<span class="token operator">=</span><span class="token string">'data_day_1'</span><span class="token punctuation">,</span></span>
<span class="line">         twinning_method<span class="token operator">=</span><span class="token string">'mcmc'</span><span class="token punctuation">,</span></span>
<span class="line">         parallelize<span class="token operator">=</span>parallelize<span class="token punctuation">,</span></span>
<span class="line">         n_steps<span class="token operator">=</span><span class="token number">5000</span><span class="token punctuation">,</span></span>
<span class="line">         u2ss<span class="token operator">=</span>u2ss<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>For more information on the twinning procedure see the <RouteLink to="/documentation/twinning_procedure.html">Twinning Procedure</RouteLink> page.</p>
<h2 id="step-2-run-replay-simulations" tabindex="-1"><a class="header-anchor" href="#step-2-run-replay-simulations"><span>Step 2: Run replay simulations</span></a></h2>
<p>Now that we have the digital twin created, it's time to replay using the <code v-pre>rbg.replay()</code> method. For more details
see the <RouteLink to="/documentation/replaying.html">Replaying</RouteLink> page.</p>
<p>The possibilities are several, but for now let's just see what happens if we run a replay using the same input data used for twinning:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line">replay_results <span class="token operator">=</span> rbg<span class="token punctuation">.</span>replay<span class="token punctuation">(</span>data<span class="token operator">=</span>data<span class="token punctuation">,</span> bw<span class="token operator">=</span>bw<span class="token punctuation">,</span> save_name<span class="token operator">=</span><span class="token string">'data_day_1'</span><span class="token punctuation">,</span></span>
<span class="line">                            twinning_method<span class="token operator">=</span><span class="token string">'mcmc'</span><span class="token punctuation">,</span></span>
<span class="line">                            save_workspace<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">,</span></span>
<span class="line">                            u2ss<span class="token operator">=</span>u2ss<span class="token punctuation">,</span></span>
<span class="line">                            save_suffix<span class="token operator">=</span><span class="token string">'_step_2a'</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>It is possible to visualize the results of the simulation using:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line">Visualizer<span class="token punctuation">.</span>plot_replay_results<span class="token punctuation">(</span>replay_results<span class="token punctuation">,</span> data<span class="token operator">=</span>data<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>and analyzing the results using:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line">analysis <span class="token operator">=</span> Analyzer<span class="token punctuation">.</span>analyze_replay_results<span class="token punctuation">(</span>replay_results<span class="token punctuation">,</span> data<span class="token operator">=</span>data<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Fit MARD: %.2f %%'</span> <span class="token operator">%</span> analysis<span class="token punctuation">[</span><span class="token string">'median'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'twin'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'mard'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Mean glucose: %.2f mg/dl'</span> <span class="token operator">%</span> analysis<span class="token punctuation">[</span><span class="token string">'median'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'glucose'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'variability'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'mean_glucose'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>As a second example, we can simulate what happens with different inputs, for example when we reduce insulin by 30%.
To do that run:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line">data<span class="token punctuation">.</span>bolus <span class="token operator">=</span> data<span class="token punctuation">.</span>bolus <span class="token operator">*</span> <span class="token number">.7</span></span>
<span class="line">replay_results <span class="token operator">=</span> rbg<span class="token punctuation">.</span>replay<span class="token punctuation">(</span>data<span class="token operator">=</span>data<span class="token punctuation">,</span> bw<span class="token operator">=</span>bw<span class="token punctuation">,</span> save_name<span class="token operator">=</span>save_name<span class="token punctuation">,</span></span>
<span class="line">                            twinning_method<span class="token operator">=</span><span class="token string">'mcmc'</span><span class="token punctuation">,</span></span>
<span class="line">                            save_workspace<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">,</span></span>
<span class="line">                            u2ss<span class="token operator">=</span>u2ss<span class="token punctuation">,</span></span>
<span class="line">                            save_suffix<span class="token operator">=</span><span class="token string">'_step_2b'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Visualize results</span></span>
<span class="line">Visualizer<span class="token punctuation">.</span>plot_replay_results<span class="token punctuation">(</span>replay_results<span class="token punctuation">)</span></span>
<span class="line"><span class="token comment"># Analyze results</span></span>
<span class="line">analysis <span class="token operator">=</span> Analyzer<span class="token punctuation">.</span>analyze_replay_results<span class="token punctuation">(</span>replay_results<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Print, for example, the average glucose</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Mean glucose: %.2f mg/dl'</span> <span class="token operator">%</span> analysis<span class="token punctuation">[</span><span class="token string">'median'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'glucose'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'variability'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'mean_glucose'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="full-example" tabindex="-1"><a class="header-anchor" href="#full-example"><span>Full example</span></a></h2>
<p>A <code v-pre>.py</code> file with the full code of the get started example can be found in <code v-pre>example/code/get_started.py</code>.</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre><code><span class="line"><span class="token keyword">import</span> os</span>
<span class="line"><span class="token keyword">import</span> numpy <span class="token keyword">as</span> np</span>
<span class="line"><span class="token keyword">import</span> pandas <span class="token keyword">as</span> pd</span>
<span class="line"></span>
<span class="line"><span class="token keyword">from</span> multiprocessing <span class="token keyword">import</span> freeze_support</span>
<span class="line"></span>
<span class="line"><span class="token keyword">from</span> py_replay_bg<span class="token punctuation">.</span>py_replay_bg <span class="token keyword">import</span> ReplayBG</span>
<span class="line"><span class="token keyword">from</span> py_replay_bg<span class="token punctuation">.</span>visualizer <span class="token keyword">import</span> Visualizer</span>
<span class="line"><span class="token keyword">from</span> py_replay_bg<span class="token punctuation">.</span>analyzer <span class="token keyword">import</span> Analyzer</span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token keyword">if</span> __name__ <span class="token operator">==</span> <span class="token string">'__main__'</span><span class="token punctuation">:</span></span>
<span class="line">    freeze_support<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment"># Set verbosity</span></span>
<span class="line">    verbose <span class="token operator">=</span> <span class="token boolean">True</span></span>
<span class="line">    plot_mode <span class="token operator">=</span> <span class="token boolean">False</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment"># Set other parameters for twinning</span></span>
<span class="line">    blueprint <span class="token operator">=</span> <span class="token string">'multi-meal'</span></span>
<span class="line">    save_folder <span class="token operator">=</span> os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>join<span class="token punctuation">(</span>os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>abspath<span class="token punctuation">(</span><span class="token string">''</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token string">'..'</span><span class="token punctuation">,</span><span class="token string">'..'</span><span class="token punctuation">,</span><span class="token string">'..'</span><span class="token punctuation">)</span></span>
<span class="line">    parallelize <span class="token operator">=</span> <span class="token boolean">True</span></span>
<span class="line">    </span>
<span class="line">    <span class="token comment"># Load data</span></span>
<span class="line">    data <span class="token operator">=</span> pd<span class="token punctuation">.</span>read_csv<span class="token punctuation">(</span>os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>join<span class="token punctuation">(</span>os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>abspath<span class="token punctuation">(</span><span class="token string">''</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'..'</span><span class="token punctuation">,</span> <span class="token string">'data'</span><span class="token punctuation">,</span> <span class="token string">'data_day_1.csv'</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    data<span class="token punctuation">.</span>t <span class="token operator">=</span> pd<span class="token punctuation">.</span>to_datetime<span class="token punctuation">(</span>data<span class="token punctuation">[</span><span class="token string">'t'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">    </span>
<span class="line">    <span class="token comment"># Load patient_info</span></span>
<span class="line">    patient_info <span class="token operator">=</span> pd<span class="token punctuation">.</span>read_csv<span class="token punctuation">(</span>os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>join<span class="token punctuation">(</span>os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>abspath<span class="token punctuation">(</span><span class="token string">''</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'..'</span><span class="token punctuation">,</span> <span class="token string">'data'</span><span class="token punctuation">,</span> <span class="token string">'patient_info.csv'</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    p <span class="token operator">=</span> np<span class="token punctuation">.</span>where<span class="token punctuation">(</span>patient_info<span class="token punctuation">[</span><span class="token string">'patient'</span><span class="token punctuation">]</span> <span class="token operator">==</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span></span>
<span class="line">    <span class="token comment"># Set bw and u2ss</span></span>
<span class="line">    bw <span class="token operator">=</span> <span class="token builtin">float</span><span class="token punctuation">(</span>patient_info<span class="token punctuation">.</span>bw<span class="token punctuation">.</span>values<span class="token punctuation">[</span>p<span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">    u2ss <span class="token operator">=</span> <span class="token builtin">float</span><span class="token punctuation">(</span>patient_info<span class="token punctuation">.</span>u2ss<span class="token punctuation">.</span>values<span class="token punctuation">[</span>p<span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">    </span>
<span class="line">    <span class="token comment"># Instantiate ReplayBG</span></span>
<span class="line">    rbg <span class="token operator">=</span> ReplayBG<span class="token punctuation">(</span>blueprint<span class="token operator">=</span>blueprint<span class="token punctuation">,</span> save_folder<span class="token operator">=</span>save_folder<span class="token punctuation">,</span></span>
<span class="line">                   yts<span class="token operator">=</span><span class="token number">5</span><span class="token punctuation">,</span> exercise<span class="token operator">=</span><span class="token boolean">False</span><span class="token punctuation">,</span></span>
<span class="line">                   seed<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">,</span></span>
<span class="line">                   verbose<span class="token operator">=</span>verbose<span class="token punctuation">,</span> plot_mode<span class="token operator">=</span>plot_mode<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment"># Set save name</span></span>
<span class="line">    save_name <span class="token operator">=</span> <span class="token string">'data_day_1'</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment"># Step 1. Run twinning procedure</span></span>
<span class="line">    rbg<span class="token punctuation">.</span>twin<span class="token punctuation">(</span>data<span class="token operator">=</span>data<span class="token punctuation">,</span> bw<span class="token operator">=</span>bw<span class="token punctuation">,</span> save_name<span class="token operator">=</span>save_name<span class="token punctuation">,</span></span>
<span class="line">             twinning_method<span class="token operator">=</span><span class="token string">'mcmc'</span><span class="token punctuation">,</span></span>
<span class="line">             parallelize<span class="token operator">=</span>parallelize<span class="token punctuation">,</span></span>
<span class="line">             n_steps<span class="token operator">=</span><span class="token number">5000</span><span class="token punctuation">,</span></span>
<span class="line">             u2ss<span class="token operator">=</span>u2ss<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment"># Step 2a. Replay the twin with the same input data</span></span>
<span class="line">    replay_results <span class="token operator">=</span> rbg<span class="token punctuation">.</span>replay<span class="token punctuation">(</span>data<span class="token operator">=</span>data<span class="token punctuation">,</span> bw<span class="token operator">=</span>bw<span class="token punctuation">,</span> save_name<span class="token operator">=</span>save_name<span class="token punctuation">,</span></span>
<span class="line">                                twinning_method<span class="token operator">=</span><span class="token string">'mcmc'</span><span class="token punctuation">,</span></span>
<span class="line">                                save_workspace<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">,</span></span>
<span class="line">                                u2ss<span class="token operator">=</span>u2ss<span class="token punctuation">,</span></span>
<span class="line">                                save_suffix<span class="token operator">=</span><span class="token string">'_step_2a'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment"># Visualize results and compare with the original glucose data</span></span>
<span class="line">    Visualizer<span class="token punctuation">.</span>plot_replay_results<span class="token punctuation">(</span>replay_results<span class="token punctuation">,</span> data<span class="token operator">=</span>data<span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment"># Analyze results</span></span>
<span class="line">    analysis <span class="token operator">=</span> Analyzer<span class="token punctuation">.</span>analyze_replay_results<span class="token punctuation">(</span>replay_results<span class="token punctuation">,</span> data<span class="token operator">=</span>data<span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment"># Print, for example, the fit MARD and the average glucose</span></span>
<span class="line">    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Fit MARD: %.2f %%'</span> <span class="token operator">%</span> analysis<span class="token punctuation">[</span><span class="token string">'median'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'twin'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'mard'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Mean glucose: %.2f mg/dl'</span> <span class="token operator">%</span> analysis<span class="token punctuation">[</span><span class="token string">'median'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'glucose'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'variability'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'mean_glucose'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment"># Step 2b. Replay the twin with different input data (-30% bolus insulin) to experiment how glucose changes</span></span>
<span class="line">    data<span class="token punctuation">.</span>bolus <span class="token operator">=</span> data<span class="token punctuation">.</span>bolus <span class="token operator">*</span> <span class="token number">.7</span></span>
<span class="line">    replay_results <span class="token operator">=</span> rbg<span class="token punctuation">.</span>replay<span class="token punctuation">(</span>data<span class="token operator">=</span>data<span class="token punctuation">,</span> bw<span class="token operator">=</span>bw<span class="token punctuation">,</span> save_name<span class="token operator">=</span>save_name<span class="token punctuation">,</span></span>
<span class="line">                                twinning_method<span class="token operator">=</span><span class="token string">'mcmc'</span><span class="token punctuation">,</span></span>
<span class="line">                                save_workspace<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">,</span></span>
<span class="line">                                u2ss<span class="token operator">=</span>u2ss<span class="token punctuation">,</span></span>
<span class="line">                                save_suffix<span class="token operator">=</span><span class="token string">'_step_2b'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment"># Visualize results</span></span>
<span class="line">    Visualizer<span class="token punctuation">.</span>plot_replay_results<span class="token punctuation">(</span>replay_results<span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment"># Analyze results</span></span>
<span class="line">    analysis <span class="token operator">=</span> Analyzer<span class="token punctuation">.</span>analyze_replay_results<span class="token punctuation">(</span>replay_results<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment"># Print, for example, the average glucose</span></span>
<span class="line">    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Mean glucose: %.2f mg/dl'</span> <span class="token operator">%</span> analysis<span class="token punctuation">[</span><span class="token string">'median'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'glucose'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'variability'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'mean_glucose'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


