import numpy as np


def ada_hypotreatments_handler(glucose, cho, hypotreatments, bolus, basal, time, time_index, dss):
    """
    Implements the default hypotreatment strategy: "take an hypotreatment of 10 g every 15 minutes while in hypoglycemia".

    Parameters
    ----------
    glucose: array
        An array vector as long the simulation length containing all the simulated glucose concentrations (mg/dl)
        up to time_index. The values after time_index should be ignored.
    cho: array
        An array vector as long the simulation length containing all the cho intakes (g/min) up to time_index.
        It does not contain hypotreatment intakes. The values after time_index should be ignored.
    hypotreatments: array
        An array vector as long the simulation length containing all the hypotreatment intakes (g/min) up to time_index.
        If the scenario is single meal, hypotreatments will contain only the hypotreatments generated by this function
        during the simulation. If the scenario is multi-meal, hypotreatments will ALSO contain the hypotreatments already
        present in the given data that labeled as such. The values after time_index should be ignored.
    bolus: array
        An array vector as long the simulation length containing all the insulin boluses (U/min) up to time_index.
        The values after time_index should be ignored.
    basal: array
        An array vector as long the simulation length containing all the insulin basal (U/min) up to time_index.
        The values after time_index should be ignored.
    time: array
        An array vector as long the simulation length containing the time corresponding to the current step (hours) up to time_index.
        The values after time_index should be ignored.
    time_index: int
        The index corresponding to the current simulation step of the replay simulation.
    dss: DSS
        An object that represents the hyperparameters of the integrated decision support system.

    Returns
    -------
    ht: float
        The hypotreatment to administer at time[time_index+1].
    dss: DSS
        An object that represents the hyperparameters of the integrated decision support system.
        dss is also an output since it contains hypotreatments_handler_params that beside being a
        dict that contains the parameters to pass to  this function, it also serves as memory area.
        It is possible to store values inside it and the ada_hypotreatments_handler function will be able
        to access to them in the next call of the function.

    Raises
    ------
    None

    See Also
    --------
    None

    Examples
    --------
    None
    """
    ht = 0

    # If glucose is lower than 70...
    if glucose[time_index] < 70:

        # ...and if there are no CHO intakes in the last 15 minutes, then take an HT
        if time_index >= 15 and not np.any(hypotreatments[(time_index-15+1):time_index+1]):

            ht = 15

    return ht, dss

def corrects_above_250_handler(glucose, cho, hypotreatments, bolus, basal, time, time_index, dss):
    """
    Implements the default correction bolus strategy: "take a correction bolus of 1 U every 1 hour while above 250 mg/dl".

    Parameters
    ----------
    glucose: array
        An array vector as long the simulation length containing all the simulated glucose concentrations (mg/dl)
        up to time_index. The values after time_index should be ignored.
    cho: array
        An array vector as long the simulation length containing all the cho intakes (g/min) up to time_index.
        It does not contain hypotreatment intakes. The values after time_index should be ignored.
    hypotreatments: array
        An array vector as long the simulation length containing all the hypotreatment intakes (g/min) up to time_index.
        If the scenario is single meal, hypotreatments will contain only the hypotreatments generated by this function
        during the simulation. If the scenario is multi-meal, hypotreatments will ALSO contain the hypotreatments already
        present in the given data that labeled as such. The values after time_index should be ignored.
    bolus: array
        An array vector as long the simulation length containing all the insulin boluses (U/min) up to time_index.
        The values after time_index should be ignored.
    basal: array
        An array vector as long the simulation length containing all the insulin basal (U/min) up to time_index.
        The values after time_index should be ignored.
    time: array
        An array vector as long the simulation length containing the time corresponding to the current step (hours) up to time_index.
        The values after time_index should be ignored.
    time_index: int
        The index corresponding to the current simulation step of the replay simulation.
    dss: DSS
        An object that represents the hyperparameters of the integrated decision support system.

    Returns
    -------
    cb: float
        The correction bolus to administer at time[time_index+1].
    dss: DSS
        An object that represents the hyperparameters of the integrated decision support system.
        dss is also an output since it contains correction_boluses_handler_params that beside being a
        dict that contains the parameters to pass to  this function, it also serves as memory area.
        It is possible to store values inside it and the corrects_above_250_handler function will be able
        to access to them in the next call of the function.

    Raises
    ------
    None

    See Also
    --------
    None

    Examples
    --------
    None
    """

    cb = 0

    # If glucose is higher than 250...
    if glucose[time_index] > 100:

        # ...and if there are no boluses in the last 60 minutes, then take a CB
        if time_index >= 60 and not np.any(bolus[(time_index - 60 + 1):time_index + 1]):
            cb = 1

    return cb, dss

def default_basal_handler():
    #TODO: implement the function
    pass
def default_meal_generator_handler():
    #TODO: implement the function
    pass
def standard_bolus_calculator_handler():
    #TODO: implement the function
    pass
